#!/usr/bin/env python3
#-*- coding: utf-8 -*-
## Created on 2025-07-20 at 19:15:01 CEST by David Gaspard (ORCID 0000-0002-4449-8782) <david.gaspard@espci.fr> under the MIT License.
## Python script to plot a mesh file. The input data must have the form [x, y, north, south, east, west].
import sys, os, datetime, csv
import numpy as np
import compile_tikz

MY_COPYRIGHT = "(c) 2025 David GASPARD (ORCID 0000-0002-4449-8782) <david.gaspard@espci.fr>"

def boundary_to_tikz_code(data):
    """
    Returns a TikZ code version of the given 'data', a list of dictionaries generated by csv.DictReader().
    The data contains the fields [x, y, north, south, east, west]. The components 'x' and 'y' are assumed to be integers, 
    and the direction components can be either point indices or boundary conditions ('mirror', 'open', 'input', or 'output').
    """
    string = "\\begin{scope}[mirror/.style={black, very thin, line cap=round}, open/.style={green, line cap=round}, input/.style={red!80, line cap=round}, output/.style={blue!80, line cap=round}]%\n"
    
    for p in data:
        if (not p['north'].isdigit()):
            x0 = int(p['x']) - 0.5;
            y0 = int(p['y']) + 0.5;
            x1 = int(p['x']) + 0.5;
            y1 = int(p['y']) + 0.5;
            string += "\\draw[{bnd}] (axis cs:{x0}, {y0}) -- (axis cs:{x1}, {y1});\n".format(bnd=p['north'], x0=x0, y0=y0, x1=x1, y1=y1)
        if (not p['south'].isdigit()):
            x0 = int(p['x']) + 0.5;
            y0 = int(p['y']) - 0.5;
            x1 = int(p['x']) - 0.5;
            y1 = int(p['y']) - 0.5;
            string += "\\draw[{bnd}] (axis cs:{x0}, {y0}) -- (axis cs:{x1}, {y1});\n".format(bnd=p['south'], x0=x0, y0=y0, x1=x1, y1=y1)
        if (not p['east'].isdigit()):
            x0 = int(p['x']) + 0.5;
            y0 = int(p['y']) + 0.5;
            x1 = int(p['x']) + 0.5;
            y1 = int(p['y']) - 0.5;
            string += "\\draw[{bnd}] (axis cs:{x0}, {y0}) -- (axis cs:{x1}, {y1});\n".format(bnd=p['east'], x0=x0, y0=y0, x1=x1, y1=y1)
        if (not p['west'].isdigit()):
            x0 = int(p['x']) - 0.5;
            y0 = int(p['y']) - 0.5;
            x1 = int(p['x']) - 0.5;
            y1 = int(p['y']) + 0.5;
            string += "\\draw[{bnd}] (axis cs:{x0}, {y0}) -- (axis cs:{x1}, {y1});\n".format(bnd=p['west'], x0=x0, y0=y0, x1=x1, y1=y1)
    
    return string + "\\end{scope}"

def plot_mesh(args):
    """
    Generate Tikz code to plot the mesh file (CSV format) given in the first argument: args[1]='filename'.
    """
    ## Check if the number of arguments is correct:
    if (len(args) != 2):
        print("[USAGE] " + args[0] + " MESH_FILE")
        return 1
    
    mesh_file = args[1]
    file_path = os.path.splitext(mesh_file)[0]  ## The file path is the filename without its extension (used to write new files). 
    
    try:
        fp = open(mesh_file, 'r')
    except IOError as e:
        print("[ERROR] Field file '" + mesh_file + " not found, aborting now...")
        return 1
    
    data = list(csv.DictReader((line for line in fp if not line.startswith('%')), skipinitialspace=True))
    
    xmesh = np.asarray([int(p['x']) for p in data], dtype=int)
    ymesh = np.asarray([int(p['y']) for p in data], dtype=int)
    
    xmin = xmesh.min()
    xmax = xmesh.max()
    ymin = ymesh.min()
    ymax = ymesh.max()
    
    tikz_code = """%% Generated on {timestamp} by {my_program} {my_copyright}
\\begin{{tikzpicture}}%
\\begin{{axis}}[%
    title={{\\detokenize{{{mesh_file}}}}},
    xlabel={{{xlabel}}},
    ylabel={{{ylabel}}},
    xmin={xmin}, xmax={xmax},
    ymin={ymin}, ymax={ymax},
    %%legend style={{at={{(1, 1)}}, anchor=center, cells={{anchor=west}}}},
    table/col sep=comma,
    axis equal,
    enlargelimits=true, %% Allow for larger view.
]%
%%\\addplot[mark=*, black!20, mark size=0.2, only marks] table[x=x,y=y]{{\\jobname.csv}};
{boundary_code}
\\end{{axis}}%
\\end{{tikzpicture}}%""".format(
        timestamp = datetime.datetime.now().astimezone().strftime("%F at %T %z"),
        my_program = args[0],
        my_copyright = MY_COPYRIGHT,
        mesh_file = mesh_file,
        xlabel = "$x$",
        ylabel = "$y$",
        xmin   = xmin-0.5,
        xmax   = xmax+0.5,
        ymin   = ymin-0.5,
        ymax   = ymax+0.5,
        boundary_code = boundary_to_tikz_code(data)
    )
    
    ## Export the TikZ code to a file and compile it:
    tikz_file = file_path + '.tikz'
    print("[INFO] Writing TikZ file: '" + tikz_file + "'...")
    open(tikz_file, 'w').write(tikz_code)
    compile_tikz.compile_tikz(tikz_file) ## Compile the TikZ file.
    
    fp.close()
    return 0

if (__name__ == '__main__'):
    exit(plot_mesh(sys.argv))
